# Generated by Django 2.2.3 on 2019-07-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('updated_at', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255)),
                ('status', models.CharField(default='publish', max_length=30)),
            ],
        ),
    ]
