# Generated by Django 2.2.3 on 2019-07-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0002_auto_20190713_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
