# Generated by Django 2.2.3 on 2019-07-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0006_slider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='Sliders',
        ),
    ]
