# Generated by Django 2.2.3 on 2019-07-18 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0007_auto_20190717_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('image', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('status', models.CharField(default='publish', max_length=30)),
                ('readmore_link', models.CharField(max_length=255)),
            ],
        ),
    ]
