# Generated by Django 2.2.3 on 2019-07-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0008_homeservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservices',
            name='readmore_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
