# Generated by Django 2.2.3 on 2019-07-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0010_auto_20190718_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeservices',
            name='readmore_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
